### PR TITLE
fix(types): add webdriver.promise and webdriver.WebElement to namespace

### LINKED ISSUE #3391: add promise and webelement to protractor namespace

### PR DESCRIPTION
**Pull request by cnishina**
closes #3391

### CODE REVIEW

**Comment by juliemr** [comment]
Looks good, thanks for the quick fix!

File: lib/ptor.ts [hunk 1]
```diff
@@ -16,19 +16,8 @@ export namespace protractor {
...
-    delayed: webdriver.promise.delayed,
-    filter: webdriver.promise.filter,
-    fulfilled: webdriver.promise.fulfilled,
-    fullyResolved: webdriver.promise.fullyResolved,
-    isPromise: webdriver.promise.isPromise,
-    rejected: webdriver.promise.rejected,
-    thenFinally: webdriver.promise.thenFinally,
-    when: webdriver.promise.when
-  };
+  export let promise = webdriver.promise;
```
Comment (Droogans) [inline lib/ptor.ts]: :+1:
