### PR TITLE
fix(local): allow local driver provider to use gecko driver from config

### LINKED ISSUE #4408: Why must set the webdriver.gecko.driver system property?
Bug report
---

- Node Version: `6.10.3`
- Protractor Version: `5.1.2`
- Angular Version: `4.2.6`
- Browser(s): `Firefox 52.2.0 (64-bit), Google Chrome 59`
- Operating System and Version `RHEL 7`
- Your protractor configuration file: Angular CLI 1.2.0 defaults +
```
    capabilities: {
        browserName: 'firefox',
        marionette: true
    },
    directConnect: false,
    localSeleniumStandaloneOpts: {
        jvmArgs: ['-Dwebdriver.gecko.driver=/home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.18.0']
    },
```
- A relevant example test: Not needed, issue is driver-specific, and when driver is OK, tests pass.
- Output from running the test:

When I specify no `jvmArgs` in the configuration file, I get:

```
[13:54:20] I/launcher - Running 1 instances of WebDriver
[13:54:20] I/local - Starting selenium standalone server...
[13:54:24] I/local - Selenium standalone server started at http://10.20.204.182:59199/wd/hub
[13:54:25] E/launcher - The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
```

Otherwise everything is OK and tests are executed:

```
[13:55:03] I/launcher - Running 1 instances of WebDriver
[13:55:03] I/local - Starting selenium standalone server...
[13:55:05] I/local - Selenium standalone server started at http://10.20.204.182:33088/wd/hub
Jasmine started
(...)
```

But specifying the full path to the GeckoDriver defeats the purpose of the webdriver-manager which should just provide this setting for me, including whatever version is available. I shouldn't be setting this `jvmArg` property, it doesn't make any sense. As we don't do the same with Chrome, which just works.

- Steps to reproduce the bug:

I'm using Angular CLI 1.2.0, and [the developers there provide no support in this regard](https://github.com/angular/angular-cli/issues/6924), so I came here.

### LINKED ISSUE #4411: DriverProvider for local: No option to set gecko driver
We check to see if chrome is set as a capability and use it when launching locally but no other drivers are provided. At a minimum we might want to also include gecko driver.

https://github.com/angular/protractor/blob/master/lib/driverProviders/local.ts#L59

We should allow for the driver path via the config file and if not to default to the webdriver-manager's downloaded binaries.

### PR DESCRIPTION
**Pull request by cnishina**
- Add gecko driver as configuration option to be used in the local
  driver provider.
- Nit fixes to use string[] over Array<string> in the configParser.ts.
- Add functionality to addDefaultBinaryLocs_ to use the geckoDriver
  value set in the config or to check locally in the
  webdriver-manager/selenium folder.
- Fix transpile errors in locator. Missing toString in ProtractorLocator
  interface.
- Fix transpile errors in element. Cast wdpromise.Promise<{}> to
  wdpromise.Promise<T>.
- xit spec/basic/action_spec.js based on
  [selenium-webdriver issue #3693](SeleniumHQ/selenium#3693).
  Added a // TODO comment to remove xit when selenium-webdriver resolves issue.

closes #4408 and closes #4411.

### CODE REVIEW

**Comment by heathkit** [comment]
Circle fails clang-format. Do we need to update? Which version are you using?

File: lib/configParser.ts [hunk 1]
```diff
@@ -55,9 +55,9 @@ export class ConfigParser {
    * @return {Array} The resolved file paths.
    */
   public static resolveFilePatterns(
-      patterns: Array<string>|string, opt_omitWarnings?: boolean,
```
Comment (heathkit) [inline lib/configParser.ts]: Yay!

**Comment by cnishina** [comment]
Out of practice. I force pushed the branch but I forgot to push my changes to the branch. 🤦‍♂️

**Comment by cnishina** [comment]
Hmmm....

```
Failures:
1) using an ActionSequence should drag and drop
  Message:
    Expected '5' to equal '10'.
  Stack:
    Error: Failed expectation
        at UserContext.<anonymous> (/home/ubuntu/protractor/spec/basic/actions_spec.js:15:45)
        at /home/ubuntu/protractor/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/ubuntu/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/ubuntu/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
```

... but '5' is equal to '10'! _Pounds the square peg in the circular hole_. Alright I'll go fix this too.

**Comment by wswebcreation** [comment]
@cnishina 

This is the circleCI issue @heathkit  already raised

See the ticket, looks like an issue with Chromedriver not being able to interact in a good way with a HTML5 slider

**Comment by cnishina** [comment]
Looks like it has something to do with: https://github.com/SeleniumHQ/selenium/issues/3693

**Comment by cnishina** [comment]
Nope, directConnect with Firefox:
```
[17:51:33] I/launcher - Running 1 instances of WebDriver
[17:51:33] I/direct - Using FirefoxDriver directly...
[17:51:35] E/launcher - Unable to parse new session response: {"value": {"sessionId":"b90252dc-4ba0-f642-8c27-9cbb7fce6548","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":11029,"moz:profile":"/var/folders/ft/1c7_rwcx16xcckqq1sl43b2m0000gn/T/rust_mozprofile.8OkiB8FXC1Sh","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
[17:51:35] E/launcher - WebDriverError: Unable to parse new session response: {"value": {"sessionId":"b90252dc-4ba0-f642-8c27-9cbb7fce6548","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":11029,"moz:profile":"/var/folders/ft/1c7_rwcx16xcckqq1sl43b2m0000gn/T/rust_mozprofile.8OkiB8FXC1Sh","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
    at doSend.then.response (/Users/craignishina/src/protractor/node_modules/selenium-webdriver/lib/http.js:445:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/craignishina/src/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/Users/craignishina/src/protractor/node_modules/selenium-webdriver/firefox/index.js:640:55)
    at Direct.getNewDriver (/Users/craignishina/src/protractor/built/driverProviders/direct.js:96:33)
    at Runner.createBrowser (/Users/craignishina/src/protractor/built/runner.js:195:43)
    at q.then.then (/Users/craignishina/src/protractor/built/runner.js:339:29)
    at _fulfilled (/Users/craignishina/src/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/craignishina/src/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/craignishina/src/protractor/node_modules/q/q.js:796:13)
    at /Users/craignishina/src/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/craignishina/src/protractor/node_modules/q/q.js:137:13)
```

**Comment by cnishina** [comment]
Also does not work with directConnect for Chrome. 👎

**Comment by cnishina** [comment]
Does anyone have issues with me commenting out this test?

**Comment by cnishina** [comment]
Per the issue above, we could wait for selenium-webdriver release or comment out the test and revisit it later.

File: spec/basicConf.js [hunk 2]
```diff
@@ -13,6 +13,8 @@ exports.config = {
 
   // Exclude patterns are relative to this directory.
   exclude: [
+    // TODO(cnishina): update when mouseMoveTo works in the next release of selenium-webdriver.
+    'basic/action_spec.js',
```
Comment (heathkit) [inline spec/basicConf.js]: Instead of doing this, could you change the test in action_spec.js to 'xit()' and put the comment there? I think it'll be easier to keep track of that way.

Comment (cnishina) [inline spec/basicConf.js]: Yes. Somehow this does not work anyway. I'll move the `// TODO` comment

**Comment by wswebcreation** [comment]
@cnishina 

Just a question, but isn't it "dangerous" to merge this PR in the source saying it's fixed if there isn't a new release to npm for this?

Or will there be a release today?
