### PR TITLE
fix(export): export selenium-webdriver

### LINKED ISSUE #2092: Exposing protractor/node_modules/selenium-webdriver/remote.FileDetector via protractor object
remote.FileDetector is useful to do file upload to a browser running on a remote selenium server. Currently to use this one has to do 
```
remote = require('protractor/node_modules/selenium-webdriver/remote');
browser.driver.setFileDetector(new remote.FileDetector());
```
 It would have been ideal if remote is exposed via protractor. Something like ```browser.driver.setFileDetector(new protractor.remote.FileDetector());```

### LINKED ISSUE #3427: protractor.Button no longer available in Protractor 4+
Bug report
---

- Node Version: `6.2.2`
- Protractor Version: `4.0.2`
- Browser(s): `chrome`
- Operating System and Version `windows/macOS/linux`

`conf.js`:
```
exports.config = {
  framework: 'jasmine2',
  specs: ['./test.js'],
  jasmineNodeOpts: { defaultTimeoutInterval: 360000 },
  allScriptsTimeout: 360000,
  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      args: ['--no-sandbox']
    }
  },

  onPrepare: function () {
    browser.driver.manage().window().maximize()
  }
}
```

`test.js`:
```
describe('angularjs homepage todo list', function() {
  it('should be able to right click', function() {
    browser.get('https://angularjs.org')

    browser.actions().mouseMove(element(by.model('todoList.todoText'))).perform()
    browser.actions().click(protractor.Button.RIGHT).perform()
    browser.sleep(5000)
  })
})
```

Running `protractor conf.js`:

Works with Protractor 3.3, here's the output when running with Protractor 4.0.2:

```
Failures:
1) angularjs homepage todo list should be able to right click
  Message:
    Failed: Cannot read property 'RIGHT' of undefined
```

### PR DESCRIPTION
**Pull request by cnishina**
- rename to ProtractorBrowser to be able to export selenium-webdriver Browser as Browser
- export all selenium-webdriver items and subfolders in ptor
- update dependency tests for selenium
- add tests when protractor is installed

closes #3427 
closes #2092

### CODE REVIEW

**Comment by cnishina** [comment]
Needs testing.

**Comment by cnishina** [comment]
`ensure globals are exported from the namespace` https://github.com/angular/protractor/issues/3437

File: globals.ts [hunk 1]
```diff
@@ -1,28 +1,21 @@
...
-export var browser: Browser = global['protractor']['browser'];
-export var element: ElementHelper = global['protractor']['element'];
-export var by: ProtractorBy = global['protractor']['by'];
-export var By: ProtractorBy = global['protractor']['By'];
-export var $: (search: string) => ElementFinder = global['protractor']['$'];
-export var $$: (search: string) => ElementArrayFinder = global['protractor']['$$'];
-export var ExpectedConditions: ProtractorExpectedConditions =
-    global['protractor']['ExpectedConditions'];
+export let protractor: Ptor = global['protractor'];
+export let browser: ProtractorBrowser = global['protractor']['browser'];
```
Comment (juliemr) [inline globals.ts]: Can we not do: `export let browser: ProtractorBrowser = protractor.['browser'];`?

File: lib/ptor.ts [hunk 2]
```diff
@@ -1,36 +1,54 @@
...
+  WebDriver = webdriver.WebDriver;
+  WebElement = webdriver.WebElement;
+  WebElementPromise = webdriver.WebElementPromise;
+  error = webdriver.error;
+  logging = webdriver.logging;
+  promise = webdriver.promise;
+  util = webdriver.util;
+  Command = require('selenium-webdriver/lib/command').Command;
+  CommandName = require('selenium-webdriver/lib/command').Name;
+  firefox = require('selenium-webdriver/firefox');
```
Comment (juliemr) [inline lib/ptor.ts]: so it can be accessed as `protractor.firefox`... I'm not thrilled with this not being differentiated from things off of `webdriver`. What about `protractor.utils.firefox`, `protractor.utils.remote`, etc?

File: spec/install/typings.json [hunk 3]
```diff
@@ -0,0 +1,9 @@
+{
+  "name": "protractor-install",
+  "dependencies": {},
+  "globalDependencies": {
+    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
+    "node": "registry:dt/node#6.0.0+20160802155038",
+    "rimraf": "registry:dt/rimraf#0.0.0+20160317120654"
```
Comment (juliemr) [inline spec/install/typings.json]: rimraf is only used in the js file, so we shouldn't need it, right?

File: spec/install/conf.ts [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import {Config} from 'protractor';
+
+export let config: Config = {
+  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
```
Comment (juliemr) [inline spec/install/conf.ts]: Do we need to use a real address here? Can we either a) get it from the environment file,or b) just use the mock since we're not actually using the webdriver server?

File: globals.ts (hunk 1 above)
Comment (cnishina) [inline globals.ts]: Yes. `protractor.browser` or `protractor['browser']`

File: lib/ptor.ts (hunk 2 above)
Comment (cnishina) [inline lib/ptor.ts]: Sure, although we are exporting `util`. Is it weird to also have `utils`?

File: spec/install/typings.json (hunk 3 above)
Comment (cnishina) [inline spec/install/typings.json]: Yes...will remove this. Originally test.js was in typescript and I was using rimraf in that.

File: spec/install/conf.ts (hunk 4 above)
Comment (cnishina) [inline spec/install/conf.ts]: This would be a great place for a mock.

File: globals.ts (hunk 1 above)
Comment (juliemr) [inline globals.ts]: That seems simpler, let's change to that then.

File: lib/ptor.ts (hunk 2 above)
Comment (juliemr) [inline lib/ptor.ts]: Naming things is hard. I'm not tied to `utils`, just wanted to ensure that it's namespaced somehow. What about `protractor.sub.remote`?

Comment (cnishina) [inline lib/ptor.ts]: Naming things is hard. `sub` sounds good to me.

Comment (cnishina) [inline lib/ptor.ts]: Fixed a typo and missing test. `util` should have been `until`. Putting `firefox`, `http`, and `remote` in `utils`.

File: lib/ptor.ts [hunk 5]
```diff
@@ -1,36 +1,56 @@
...
+  Command = require('selenium-webdriver/lib/command').Command;
+  CommandName = require('selenium-webdriver/lib/command').Name;
+  utils = {
+    firefox: require('selenium-webdriver/firefox'),
+    http: require('selenium-webdriver/http'),
+    remote: require('selenium-webdriver/remote')
+  }
 }
+
+export var Protractor = new Ptor();
```
Comment (juliemr) [inline lib/ptor.ts]: I think this should be lowercase, since it's an instance.

export var protractor = new Ptor();

**Comment by juliemr** [comment]
One more thing, then LGTM
